[SIMU] Corrections on simulation script

diff --git a/modules/cordic/simulations/run_simulation b/modules/cordic/simulations/run_simulation
--- a/modules/cordic/simulations/run_simulation
+++ b/modules/cordic/simulations/run_simulation
@@ -20,7 +20,7 @@ if [[ -z ${PROJECT_DIR} ]]; then
 fi
 
 # Check number of parameters
-if [ $# -lt 1 ] && [ $# -gt 3 ]; then
+if [ $# -lt 1 ] || [ $# -gt 3 ]; then
 	echo "ERROR: Illegal number of parameters"
 	echo "./run_simulation <top_module> (--synthesis) (--synthVersion=<>)"
 	exit 1
@@ -28,24 +28,23 @@ fi
 
 # Check flags
 fromSynth=0
-if [ -n $2 ]; then
-	if [ $2 == "--synthesis" ]; then
+if [[ ! -z $2 ]]; then
+	if [[ $2 == "--synthesis" ]]; then
 		fromSynth=1
-		if [ $(echo $3 | cut -f 1 -d "=") == "--synthVersion" ]; then
+		if [[ $(echo $3 | cut -f 1 -d "=") == "--synthVersion" ]]; then
 			synthVersion=$(echo $3 | cut -f 2 -d "=")
-		elif [ -n $3 ]
-			echo "ERROR: Invalid flag $3"
+		elif [[ -n $3 ]]; then
+			echo "ERROR: Invalid argument $3"; exit 1
 		fi
-	elif [ $(echo $2 | cut -f 1 -d "=") == "--synthVersion" ]; then
-		if [ -n $3 ] && [ $3 != "--synthesis"]; then
-			echo "ERROR: Invalid argument $3"
-			exit 1
+	elif [[ $(echo $2 | cut -f 1 -d "=") == "--synthVersion" ]]; then
+		if [| -n $3 ]] && [[ $3 != "--synthesis" ]]; then
+			echo "ERROR: Invalid argument $3"; exit 1
 		else
 			fromSynth=1
 			synthVersion=$(echo $2 | cut -f 2 -d "=")
 		fi
 	else
-		echo "ERROR: Invalid argument $2"
+		echo "ERROR: Invalid argument $2"; exit 1
 	fi
 fi
 
@@ -58,15 +57,18 @@ if [[ $PWD != "${PROJECT_DIR}/modules/${IPname}/simulations" ]]; then
 fi
 
 # Configuration of environment variables
-export MODULE_MAIN_FOLDER="${PROJECT_DIR}/module/${IPname}/"
+export MODULE_MAIN_FOLDER="${PROJECT_DIR}/modules/${IPname}/"
 export MODULE_CONFIG_FOLDER="${PROJECT_DIR}config/"
 export MODULE_LIBS_FOLDER="${MODULE_MAIN_FOLDER}libs/"
 export MODULE_RTL_FOLDER="${MODULE_MAIN_FOLDER}rtl/"
-export MODULE_ASIC_FOLDER="${MODULE_MAIN_FOLDER}/asic/"
+export MODULE_ASIC_FOLDER="${MODULE_MAIN_FOLDER}asic/"
 export MODULE_BENCH_FOLDER="${MODULE_MAIN_FOLDER}testbench/"
 
 # Creating lib folders
-rm -r ${MODULE_LIBS_FOLDER}
+if [[ -d ${MODULE_LIBS_FOLDER} ]]; then
+	rm -r ${MODULE_LIBS_FOLDER}
+fi
+
 if [[ ! -d ${MODULE_LIBS_FOLDER} ]]; then
 	mkdir -p "${MODULE_LIBS_FOLDER}lib_RTL"
 	mkdir -p "${MODULE_LIBS_FOLDER}lib_BENCH"
@@ -97,38 +99,40 @@ if [ ${fromSynth} -eq 1 ]; then
 		while [ -d ${MODULE_ASIC_FOLDER}/synth/synthesis_${iter} ]; do
 			iter=$((iter+1))
 		done
-		if [ $iter -nq 0]
+		if [[ $iter -ne 0 ]]; then
 			synthVersion=$((iter-1))
+		else
+			synthVersion=0
 		fi
-		synthDir="synthesis_${synthVersion}"
 	fi
+	
+	synthDir="${MODULE_ASIC_FOLDER}synth/synthesis_${synthVersion}"
 
 	if [ -d $synthDir ]; then
-		echo "Using RTL synthesis netlist version ${synthVersion} for simulation"
+		echo "Using synthesis netlist version ${synthVersion} for simulation"
 	else
-		echo "ERROR: $synthDir: No such file or directory"
-		exit 1
+		echo "ERROR: $synthDir: No such file or directory"; exit 1
+	fi
 else
 	echo "Using RTL source files for simulation"
 fi
 
 # Compiles and simulates design
 if [ $fromSynth -eq 1 ]; then
-	vlog +acc -work lib_${IPname}_SYNTH ${MODULE_ASIC_FOLDER}synth/${synthDir}/synthesis_RTL/*.v
+	vlog +acc -work lib_${IPname}_SYNTH ${synthDir}/synthesis_RTL/*.v
 	vlog +acc -sv -work lib_${IPname}_TB ${MODULE_BENCH_FOLDER}src/*.sv -L lib_${IPname}_SYNTH
 	
 	# Run simulation
 	vsim -debugDB -lib lib_${IPname}_TB -L lib_${IPname}_SYNTH -L ${AMS_DIR}/verilog/c35b4/lib_Questa107c/c35_CORELIB $top_module
 else
-	if [ `ls -1 ${MODULE_RTL_FOLDER}src/*.sv 2>/dev/null | wc -l ` -gt 0 ]; then
+	if [ `ls -1 ${MODULE_RTL_FOLDER}src/*.sv 2>/dev/null | wc -l` -gt 0 ]; then
+		echo "Compile SystemVerilog files"
 		vlog +acc -sv -work lib_${IPname} ${MODULE_RTL_FOLDER}src/*.sv
-	fi
-
-	if [ `ls -1 ${MODULE_RTL_FOLDER}src/*.v 2>/dev/null | wc -l ` -gt 0 ]; then
+	elif [ `ls -1 ${MODULE_RTL_FOLDER}src/*.v 2>/dev/null | wc -l` -gt 0 ]; then
+		echo "Compile Verilog files"
 		vlog +acc -work lib_${IPname} ${MODULE_RTL_FOLDER}src/*.v
-	fi
-	
-	if [ `ls -1 ${MODULE_RTL_FOLDER}src/*.vhd 2>/dev/null | wc -l ` -gt 0 ]; then
+	elif [ `ls -1 ${MODULE_RTL_FOLDER}src/*.vhd 2>/dev/null | wc -l` -gt 0 ]; then
+		echo "Compile VHDL files"
 		vcom +acc -work lib_${IPname} ${MODULE_RTL_FOLDER}src/*.vhd
 	fi
 
